import { ContextDigest, FileContext, ParsedCode } from '../types';

/**
 * Local-only context analyzer that doesn't require any AI APIs
 * Uses rule-based heuristics and templates to generate context
 */
export class LocalAnalyzer {
  async analyzeContext(fileContext: FileContext, parsedCode: ParsedCode, fileContent: string): Promise<ContextDigest> {
    // Build context digest using pure logic - no AI needed
    const primaryPurpose = this.inferPrimaryPurpose(fileContext, parsedCode, fileContent);
    const knownConflicts = this.detectPotentialConflicts(parsedCode, fileContent);

    return {
      lastModifiedBy: fileContext.svnInfo?.lastAuthor || 'Unknown',
      lastModifiedDate: fileContext.svnInfo?.lastCommitDate.toLocaleDateString() || 'Unknown',
      primaryPurpose,
      directCalls: fileContext.directCalls,
      knownDataConflicts: knownConflicts,
      relatedFiles: fileContext.relatedFiles.map(rf => rf.path),
      recentChanges: fileContext.svnInfo?.recentLogs.map(log =>
        `[${log.revision}] ${log.message} (${log.author})`
      ) || [],
      jiraIssues: [],
      mondayItems: [],
      additionalNotes: this.generateAdditionalNotes(fileContext, parsedCode, fileContent),
    };
  }

  async generateMarkdownSummary(digest: ContextDigest): Promise<string> {
    let markdown = '# Code Context Summary\n\n';
    markdown += `*Generated locally without AI - based on code analysis and heuristics*\n\n`;

    // Last Modified Section
    markdown += `## Last Modified\n`;
    markdown += `**By:** ${digest.lastModifiedBy}  \n`;
    markdown += `**Date:** ${digest.lastModifiedDate}\n\n`;

    // Primary Purpose Section
    markdown += `## Primary Purpose\n`;
    markdown += `${digest.primaryPurpose}\n\n`;

    // Direct Calls Section
    if (digest.directCalls.length > 0) {
      markdown += `## Direct Calls & Dependencies\n`;
      markdown += `This module calls or depends on ${digest.directCalls.length} external program(s)/module(s):\n\n`;
      digest.directCalls.forEach(call => {
        markdown += `- \`${call}\`\n`;
      });
      markdown += '\n';
    } else {
      markdown += `## Direct Calls & Dependencies\n`;
      markdown += `No external calls detected. This appears to be a self-contained module.\n\n`;
    }

    // Data Conflicts Section
    if (digest.knownDataConflicts.length > 0) {
      markdown += `## ⚠️ Known Data Conflicts & Issues\n`;
      digest.knownDataConflicts.forEach(conflict => {
        markdown += `- ${conflict}\n`;
      });
      markdown += '\n';
    }

    // Related Files Section
    if (digest.relatedFiles.length > 0) {
      markdown += `## Related Files\n`;
      const maxRelated = Math.min(digest.relatedFiles.length, 10);
      markdown += `Found ${digest.relatedFiles.length} related file(s). Showing top ${maxRelated}:\n\n`;
      digest.relatedFiles.slice(0, maxRelated).forEach(file => {
        markdown += `- ${file}\n`;
      });
      markdown += '\n';
    }

    // Recent Changes Section
    if (digest.recentChanges.length > 0) {
      markdown += `## Recent Changes (from SVN)\n`;
      const maxChanges = Math.min(digest.recentChanges.length, 5);
      digest.recentChanges.slice(0, maxChanges).forEach(change => {
        markdown += `- ${change}\n`;
      });
      markdown += '\n';
    }

    // Jira Issues Section
    if (digest.jiraIssues.length > 0) {
      markdown += `## Related Jira Issues\n`;
      digest.jiraIssues.forEach(issue => {
        markdown += `- [${issue.key}](${issue.url}): ${issue.summary} (${issue.status})\n`;
      });
      markdown += '\n';
    }

    // Monday.com Items Section
    if (digest.mondayItems.length > 0) {
      markdown += `## Related Monday.com Items\n`;
      digest.mondayItems.forEach(item => {
        markdown += `- [${item.name}](${item.url})\n`;
      });
      markdown += '\n';
    }

    // Additional Notes Section
    if (digest.additionalNotes.length > 0) {
      markdown += `## Analysis Notes\n`;
      digest.additionalNotes.forEach(note => {
        markdown += `${note}\n\n`;
      });
    }

    markdown += `---\n`;
    markdown += `*Generated by CodeContext Live (Local Mode)*\n`;

    return markdown;
  }

  private inferPrimaryPurpose(fileContext: FileContext, parsedCode: ParsedCode, fileContent: string): string {
    const parts: string[] = [];

    // Analyze based on file type
    switch (fileContext.fileType) {
      case 'COBOL':
        parts.push(this.analyzeCOBOLPurpose(parsedCode, fileContent));
        break;
      case 'VB.NET':
        parts.push(this.analyzeVBNetPurpose(parsedCode, fileContent));
        break;
      case 'C#':
        parts.push(this.analyzeCSharpPurpose(parsedCode, fileContent));
        break;
    }

    // Add function count
    if (parsedCode.functions.length > 0) {
      parts.push(`Contains ${parsedCode.functions.length} function(s)/section(s).`);
    }

    // Add data structure info
    if (parsedCode.dataStructures.length > 0) {
      parts.push(`Defines ${parsedCode.dataStructures.length} data structure(s).`);
    }

    // Add dependency info
    if (parsedCode.dependencies.length > 0) {
      parts.push(`Depends on ${parsedCode.dependencies.length} external module(s).`);
    }

    return parts.join(' ') || 'Purpose not automatically determined. Review code for details.';
  }

  private analyzeCOBOLPurpose(parsedCode: ParsedCode, fileContent: string): string {
    const content = fileContent.toLowerCase();

    // Check for CICS
    if (content.includes('exec cics')) {
      return 'CICS transaction program that handles screen-based user interactions.';
    }

    // Check for batch
    if (content.includes('accept') && content.includes('display')) {
      return 'Batch processing program with console I/O.';
    }

    // Check for file processing
    if (content.includes('file-control') || content.includes('select')) {
      return 'File processing program that reads/writes data files.';
    }

    // Check for DB2
    if (content.includes('exec sql')) {
      return 'Database program with SQL operations (likely DB2).';
    }

    // Check for subroutine
    if (content.includes('linkage section')) {
      return 'Callable subroutine/module used by other programs.';
    }

    return 'COBOL program';
  }

  private analyzeVBNetPurpose(parsedCode: ParsedCode, fileContent: string): string {
    const content = fileContent.toLowerCase();

    // Check for form
    if (content.includes('inherits system.windows.forms.form')) {
      return 'Windows Forms UI component for user interface.';
    }

    // Check for web
    if (content.includes('system.web')) {
      return 'Web application component (ASP.NET).';
    }

    // Check for data access
    if (content.includes('sqlconnection') || content.includes('sqlcommand')) {
      return 'Data access layer for database operations.';
    }

    // Check for class library
    if (content.includes('public class') && !content.includes('sub main')) {
      return 'Reusable class library component.';
    }

    return 'VB.NET component';
  }

  private analyzeCSharpPurpose(parsedCode: ParsedCode, fileContent: string): string {
    const content = fileContent.toLowerCase();

    // Check for controller
    if (content.includes('controller') && content.includes('actionresult')) {
      return 'ASP.NET MVC/API controller that handles HTTP requests.';
    }

    // Check for service
    if (content.includes('interface i') && content.includes('service')) {
      return 'Service layer component with business logic.';
    }

    // Check for repository
    if (content.includes('repository') && content.includes('dbcontext')) {
      return 'Data repository for database entity access.';
    }

    // Check for model/entity
    if (content.includes('public class') && content.includes('get; set;')) {
      return 'Data model or entity class.';
    }

    // Check for middleware
    if (content.includes('middleware') || content.includes('invoke(httpcontext')) {
      return 'ASP.NET middleware component.';
    }

    return 'C# component';
  }

  private detectPotentialConflicts(parsedCode: ParsedCode, fileContent: string): string[] {
    const conflicts: string[] = [];
    const content = fileContent.toLowerCase();

    // Check for hardcoded values
    if (this.hasHardcodedValues(fileContent)) {
      conflicts.push('Contains hardcoded values that may need configuration');
    }

    // Check for deprecated patterns
    if (content.includes('goto') && !content.includes('perform')) {
      conflicts.push('Uses GOTO statements which may make code harder to maintain');
    }

    // Check for TODO/FIXME comments
    if (content.includes('todo') || content.includes('fixme') || content.includes('hack')) {
      conflicts.push('Contains TODO/FIXME comments indicating incomplete work');
    }

    // Check for exception swallowing
    if (content.includes('catch') && content.includes('{ }')) {
      conflicts.push('May contain empty catch blocks that suppress errors');
    }

    // Check for SQL injection risk
    if (content.includes('exec sql') || content.includes('sqlcommand')) {
      if (!content.includes('parameters') && !content.includes('prepare')) {
        conflicts.push('Potential SQL injection risk - verify parameterization');
      }
    }

    // Check for multiple responsibilities
    if (parsedCode.functions.length > 20) {
      conflicts.push(`Large number of functions (${parsedCode.functions.length}) may indicate too many responsibilities`);
    }

    return conflicts;
  }

  private hasHardcodedValues(fileContent: string): boolean {
    // Simple heuristic: look for string/number literals in assignments
    const hardcodedPatterns = [
      /=\s*["'][A-Z0-9]{3,}["']/i,  // Hardcoded strings
      /=\s*\d{4,}/,                   // Hardcoded numbers (4+ digits)
    ];

    return hardcodedPatterns.some(pattern => pattern.test(fileContent));
  }

  private generateAdditionalNotes(fileContext: FileContext, parsedCode: ParsedCode, fileContent: string): string[] {
    const notes: string[] = [];

    // File size note
    const lines = fileContent.split('\n').length;
    if (lines > 1000) {
      notes.push(`⚠️ Large file (${lines} lines) - consider refactoring for maintainability.`);
    } else if (lines < 50) {
      notes.push(`ℹ️ Small file (${lines} lines) - likely a utility or helper module.`);
    } else {
      notes.push(`ℹ️ File size: ${lines} lines of code.`);
    }

    // Comment ratio
    const commentCount = parsedCode.comments.length;
    const commentRatio = lines > 0 ? (commentCount / lines) * 100 : 0;
    if (commentRatio < 5) {
      notes.push(`⚠️ Low comment ratio (${commentRatio.toFixed(1)}%) - consider adding more documentation.`);
    } else if (commentRatio > 30) {
      notes.push(`✅ Well-documented code (${commentRatio.toFixed(1)}% comments).`);
    }

    // Complexity note based on function calls
    const totalCalls = parsedCode.functions.reduce((sum, f) => sum + f.calls.length, 0);
    if (totalCalls > 50) {
      notes.push(`⚠️ High complexity - ${totalCalls} function calls detected.`);
    }

    // Last modification recency
    if (fileContext.svnInfo) {
      const daysSinceModified = Math.floor(
        (new Date().getTime() - fileContext.svnInfo.lastCommitDate.getTime()) / (1000 * 60 * 60 * 24)
      );

      if (daysSinceModified < 7) {
        notes.push(`✅ Recently modified (${daysSinceModified} day(s) ago) - likely active development.`);
      } else if (daysSinceModified > 365) {
        notes.push(`ℹ️ Last modified ${Math.floor(daysSinceModified / 365)} year(s) ago - stable or legacy code.`);
      }
    }

    // Language-specific notes
    switch (fileContext.fileType) {
      case 'COBOL':
        if (fileContent.toLowerCase().includes('exec cics')) {
          notes.push(`ℹ️ CICS program - requires CICS runtime environment.`);
        }
        if (fileContent.toLowerCase().includes('exec sql')) {
          notes.push(`ℹ️ Contains embedded SQL - requires DB2 or similar database.`);
        }
        break;

      case 'VB.NET':
        if (fileContent.toLowerCase().includes('option strict off')) {
          notes.push(`⚠️ Option Strict is OFF - may have type safety issues.`);
        }
        break;

      case 'C#':
        if (!fileContent.includes('namespace')) {
          notes.push(`⚠️ No namespace defined - may cause naming conflicts.`);
        }
        if (fileContent.includes('async Task')) {
          notes.push(`✅ Uses async/await pattern for better performance.`);
        }
        break;
    }

    return notes;
  }
}

export default new LocalAnalyzer();
